### ISSUE TITLE
Create unit tests for Massif

### ISSUE THREAD

**Issue by imbur** [viatra/massif#1]
Unit testing (without Matlab)
- Communication
- Connectors (CE - command evaluation, MC - matlabcontrol)
- SimulinkApi import/export

Idea:
- Create recorder for Matlab command results, use as oracle for tests
- Create connector for reading recorded command results

**Comment by abelhegedus** [comment]
Closing for now, added to [planning](https://github.com/viatra/massif/wiki/Planning).
