### ISSUE TITLE
Update provided example .simulink models to be in line with recent metamodel changes

### ISSUE THREAD

**Issue by imbur** [viatra/massif#117]
Changes to the metamodel recently has been made as discussed under #8

**Comment by abelhegedus** [comment]
@mayerkr please provide list of models that were still not migrated

**Comment by mayerkr** [comment]
I've only found this .simulink file which needs to be updated: https://github.com/viatra/massif/blob/master/releng/hu.bme.mit.massif.simulink.cli-package/Example.simulink
