### ISSUE TITLE
Improve URI handling in the Exporter.class

### ISSUE THREAD

**Issue by mayerkr** [viatra/massif#142]
During resource loading in the _loadSimulinkModel_ method, a file URI should be created explicitly. 
The parameter of this method is confusing,  "file path without extension" is more appropriate.

Note: Using Windows file URIs with backslashes as separators, leads to erroneous behavior during URI creation.

**Comment by abelhegedus** [comment]
Fixed by https://github.com/viatra/massif/pull/144

**Comment by abelhegedus** [comment]
Details:
* make sure API uses URI instead of String
* User interface should use EMF/Eclipse file browser to create file URI independent of operating system
