### ISSUE TITLE
Create Simulink graphical viewer using EMF-IncQuery Viewers

### ISSUE THREAD

**Issue by abelhegedus** [viatra/massif#15]
The queries are already available, though we have to select the graph visualization technology.

Possible candidates:
- Zest: easy to achieve, but no hierarchy, so it would behave like the Matlab Simulink editor, only one level at a time with drill down support
- Sirius: needs some development, but might be more future proof. It would also provide a way to get editor functionality as well.

**Comment by phanthanhliem** [comment]
Yes, I think both viewer and editor for simulink models are important.
Have you started to implement this requirement?

**Comment by abelhegedus** [comment]
We are not planning to have a graphical editor yet, but the viewer is definitely on our roadmap.

The annotated query specifications for the EMF-IncQuery Viewers framework are available ( https://github.com/FTSRG/massif/blob/master/plugins/hu.bme.mit.massif.simulink.incquery/src/hu/bme/mit/massif/models/simulink/viewer/simulinkViewer.eiq ), but it doesn't work well on Zest, since it has no hierarchy support.

**Comment by phanthanhliem** [comment]
OK, I have to study about EMF-IncQuery a litte bit to understand how it works.

**Comment by phanthanhliem** [comment]
Hi abelhegedus, imbur,

I'am trying to implement a simple viewer/editor by using Sirius.
In fact, Sirius is really a strong and easy-to-use tool. 
From the simulink metamodel (simulink.ecore), you can create rapidly a simple viewer/editor,
within an hour.
![image](https://cloud.githubusercontent.com/assets/10292378/5834569/6dbcd5dc-a15f-11e4-9c39-d19cb3de36dd.png)

My question is: what are the benefits of creating a viewer/editor from the annotated query specs?
And why creating a viewer/editor from the simulink.ecore (the traditional way) is not enough?

Regards.
PTL.

**Comment by abelhegedus** [comment]
Looks great, would you mind sharing with us your Sirius related code?

- EMF-IncQuery Viewers provides incremental maintenance of model views which may also be completely different from the concrete syntax of the metamodel. In addition, the declarative definition of views is easier to maintain than other approaches. However, from what I know, Sirius may also work similarly. Finally, the Viewers technology scales well to views with a large number of elements, and scalability only depends on the actual vizualization tool (e.g. Zest).
- If you mean the generated editor as "traditional way", that is already included (simulink.editor plugin)

**Comment by phanthanhliem** [comment]
It's ok, i'm here for sharing the source code.
I will send it to you when i've got a rather good version (may be next week).

About your answers above:
- EMF-IncQuery : i still dont understand its concepts => need to see EMF-IncQuery
- "traditional way" => in this case, I means creating graphical editor "from simulink.ecore using Sirius", to be compared with "from EMF IncQuery query specs using Sirius".

**Comment by abelhegedus** [comment]
EMF-IncQuery Viewers makes it possible to consider matches of queries as items or edges, which means you can make arbitrary abstractions from a concrete model. What is even more important, that the view model is kept up to date incrementally.

I guess Sirius also offers the first part already, but I don't know about the second part. What happens if a model loaded into a Sirius editor is changed from outside the editor (e.g. a transformation deletes and creates elements, changes some references or attributes)? Will the editor correctly update itself incrementally or at all?

**Comment by phanthanhliem** [comment]
With Sirius, of course we can create an arbirtrary abstract view from a concrete model.
For the second point, i've done a simple test:
 - modify an attribute of model.simulink by an external editor,
 - then I have to do 2 things in order to update the viewer
    + F5 to refresh the modeing project,
    + click on "refresh diagram" button 

So, in my opinion, sirius diagram can be updated. In fact, for each folder of a modeling project, sirius will generate a representation.aird for all the models of that folder. The update, then, will be done in this file.

In the architecture overview of sirius, it claims that, when we change the definition of sirius viewer, then the representation file is indeed incrementally update automatically. So when we change the data model, the view is updated incrementally or not, we have no clue. 
http://www.eclipse.org/sirius/doc/developer/Architecture_Overview.html

I'll send you the 2 plugins : 
- simulink.design for the viewer
- simulink.example for the examples models

**Comment by abelhegedus** [comment]
> modify an attribute of model.simulink by an external editor

That means you work on a different ResourceSet than the Sirius editor, and in that case atomic change notifications (SET on attribute of EObject) are not sent by EMF, instead, the whole Resource is reloaded when EMF realizes that the file changed under the loaded Resource.
Instead, to test true incrementality, you need to modify the model in the ResourceSet that is used by the editor (e.g. by writing a simple UI command and menu action that retrieves the ResourceSet from the active editor, navigates into the EObject hierarchy and sets the attribute) and observe the effects. I will also try this out when I get around to it.

> then I have to do 2 things in order to update the viewer
 * F5 to refresh the modeing project,
 * click on "refresh diagram" button

When you have to manually request an update, then the editor is _not_ incremental. With EMF-IncQuery Viewers, the view is automatically updated regardless of the source of the change.

**Comment by phanthanhliem** [comment]
Ok, i will have a look at EMF-IncQuery Viewers.

**Comment by abelhegedus** [comment]
Closing for now, added to [planning](https://github.com/viatra/massif/wiki/Planning).
