### ISSUE TITLE
Add example and documentation for MatlabEngine usage

### ISSUE THREAD

**Issue by abelhegedus** [viatra/massif#151]

**Comment by mayerkr** [comment]
"Undefined function or variable 'off'." error when using the exported with the example model "sldemo_engine_export"

**Comment by mayerkr** [comment]
Tested the exmaple models with massif wrapper, which transforms them just fine.

**Comment by mayerkr** [comment]
Further investigation reveals that the import crashes when trying to retrieve the ImporterTmpResult during executeEval in MatlabEngineAccess. Sadly no exception is thrown, the program crashes silently.

**Comment by mayerkr** [comment]
The issue was caused by running the matlabengine example from OSGi environment, and classes were not loaded properly. The examples have to be run as JUnit tests not as plug-in tests.  Also provided the needed code to set up massif in a non-eclipse environment.
