### ISSUE TITLE
Don't deploy Eclipse artifacts to Nexus

### ISSUE THREAD

**Issue by thSoft** [viatra/massif#179]
https://build.incquerylabs.com/nexus/#browse/browse:massif-releases contains Eclipse-specific artifacts, they should not be deployed.

**Comment by ujhelyiz** [comment]
Given the deployment is not slow nor the files large, and sometimes it is helpful if the latest artifacts are uploaded (e.g. see #215) I would be careful about removing the deployment of the mentioned artifacts (even if unnecessary, their present do not cause issues).

**Comment by abelhegedus** [comment]
I think we can close this and reopen if something specific comes up.
