### ISSUE TITLE
Review JavaDoc for public APIs

### ISSUE THREAD

**Issue by imbur** [viatra/massif#2]

**Comment by amdapi** [comment]
Hi, 

Is there some documentation for the Simulink APIs already existing? Or do I have something wrong in my settings that I do not see documentation for methods such as importer.getBlocks(), etc.

Cheers

**Comment by imbur** [comment]
Hi!

The mentioned method is a getter for a cache, mainly for development purposes (as it is in the comment https://github.com/FTSRG/massif/blob/master/plugins/hu.bme.mit.massif.simulink.api/src/hu/bme/mit/massif/simulink/api/Importer.java#L166). I admit that this is confusing, but the important parts of the public API are the documented methods under https://github.com/FTSRG/massif/wiki/ApiUsageExample .
Cheers,
Marci

**Comment by imbur** [comment]
Added short descriptions for the importer cache getters in d06fcdb8980aa29096ef0c5591e028eb4f946652

**Comment by abelhegedus** [comment]
Closing for now, added to [planning](https://github.com/viatra/massif/wiki/Planning).
