### ISSUE TITLE
Properties of port need to be preserved

### ISSUE THREAD

**Issue by phanthanhliem** [viatra/massif#30]
All properties of port (cf. figure below) are not considered in the current version.
![image](https://cloud.githubusercontent.com/assets/10292378/6864703/4f7e96a8-d465-11e4-8bca-3412d91a49b7.png)
But in my opinion, it is also important to preserve these information.
For example, to export the simulation data, the field "DataLogging" & "DataLoggingNameMode" is necessary for us to retrieve the result later.
![image](https://cloud.githubusercontent.com/assets/10292378/6864839/dead12a4-d466-11e4-99fc-664d0afca6ba.png)

**Comment by abelhegedus** [comment]
We retrieve the list of all properties of blocks using standard Matlab commands and those should be stored in the imported model as well. However, it is possible that in this case the properties are for the port itself (and not the port block). @imbur is it possible that we have to look at port properties as well not just block properties? I see that DefaultBlockAdapter processes all properties but the PortAdapters do not.

**Comment by imbur** [comment]
I would escalate this problem to a higher level: the property handling for every Simulink object should be revised. At the same time, we should also make default parameter value support available, if possible. This latter feature could significantly decrease import time and/or imported model size.

**Comment by abelhegedus** [comment]
Is it possible to determine at import and export time whether a given property has default value or what the default value would be?

**Comment by imbur** [comment]
We couldn't find solutions so far, but in my opinion it worth a new iteration.

**Comment by imbur** [comment]
The same [site mentioned](https://www.mathworks.com/help/simulink/slref/block-specific-parameters.html#br8pz2z) in #28 has a summary of port parameters as well so that values that are have other values than the default value could be selected for saving.

**Comment by abelhegedus** [comment]
Duplicate.
