### ISSUE TITLE
Add tracing to Simulink API

### ISSUE THREAD

**Issue by abelhegedus** [viatra/massif#34]
Related to #33 we should make it possible to turn on tracing in Eclipse to log all executed commands when importing/exporting and also give more helpful error feedback.

**Comment by imbur** [comment]
A suggestion is to add an option that allows saving both the issued MATLAB commands and the return values to a log file for better traceability.

**Comment by abelhegedus** [comment]
Closing for now, added to [planning](https://github.com/viatra/massif/wiki/Planning).
