### ISSUE TITLE
Evaluate Windows dependent code (CE server and CE connector)

### ISSUE THREAD

**Issue by imbur** [viatra/massif#4]
Windows registry is currently used for finding installed Matlabs.

**Comment by ujhelyiz** [comment]
I have looked into the code and found that it is not strictly necessary to check for installed Matlab instances to run the CE connector, given RMI connects via ports.

Given that finding out whether a Matlab instance is running before trying to connect to it allows providing better error messages, I did only turn off these checks for non-Windows OS instances; but we might consider removing them totally.

**Comment by imbur** [comment]
I looked into the topic again, and I found that now only [this part added in the last connecting commit](https://github.com/viatra/massif/blob/master/plugins/hu.bme.mit.massif.communication.commandevaluation/src/hu/bme/mit/massif/communication/commandevaluation/CEServerCommandEvaluatorFactory.java#L56-L66) is Windows-specific. However, this is only a check if there is a running MATLAB instance with the given parameters.
This is a tiny dependency, so closing the ticket.
