### ISSUE TITLE
Broken link for downloading massif components in the update site

### ISSUE THREAD

**Issue by raymerta** [viatra/massif#47]
Hi 

I'm trying to install massif and follow the installation guidelines from the [wiki](https://github.com/FTSRG/massif/wiki/UserGuide#installation) and massif component link is not working.

Right now I'm using the developer's guide to try to rebuild the component

**Comment by abelhegedus** [comment]
Please check https://github.com/IncQueryLabs/massif#update-site for up to date information.
We plan to merge the fork and this original repository soon, but there is still some planning to do.

**Comment by raymerta** [comment]
Thank you for your reply. I will check it out 👍

**Comment by abelhegedus** [comment]
Repository moved to VIATRA organization and forks merged, so the information is up-to-date.
