### ISSUE TITLE
Exporting a design holding Scope and Sub-system blocks fails

### ISSUE THREAD

**Issue by GaraziJuez** [viatra/massif#54]
Hi,

after importing a Simulink design, we are trying to export it once again in order to compare it with the original one.
However, we face different issues w.r.t. Massif exporting function when that design holds "Sub-systems" or "Scope" blocks.  2. If the design contains a "Scope" block, after importing and exporting it again, this block is transformed into "floating scope" type.

For instance, we have tried this very simply example getting the following errors: "Scope block parameter 'floating' is read-only". 

![scope_original 2](https://user-images.githubusercontent.com/20126983/29208515-b1b09192-7e8a-11e7-87a6-77ac7d43580f.png)
![scope_exported 2](https://user-images.githubusercontent.com/20126983/29208530-bae02228-7e8a-11e7-9086-b225af90fc11.png)
![scope_massif_file 3](https://user-images.githubusercontent.com/20126983/29208538-c306e180-7e8a-11e7-8283-e74f380d09db.png)

A similar issue applies to the" sldemo_clutch_import_demo..." example which is provided in the wiki. 
"Subsystem block parameter 'ActiveVariant' is read-only "."

Thank you,
Garazi

**Comment by imbur** [comment]
Thanks for reporting! This parameter used to be mutable in earlier versions of Simulink. In the planned workaround (work is in progress), both the importer and the exporter are modified, so that you will have to reimport your model.
