### ISSUE TITLE
Support for Stateflow

### ISSUE THREAD

**Issue by afpaz** [viatra/massif#55]
Hello,

I'm very interested in Massif for handling Matlab Simulink models. However, I would also like to obtain an EMF representation of Stateflow models. From what I get by looking at the source code, Stateflow charts are just being treated as blocks and their internals are ignored, is that right?

I've been trying to test the tool for this but I haven't been able to get it running on macOS within Eclipse Mars.2 and Matlab 2016b installed. At first I tried the Command Evaluation Server connector, which didn't work. Then I saw the issue posted that it only works on Windows, so I went on to try the MatlabControl connector but it didn't work either. Nothing happens after the import dialog closes. Any pointers?

I even tried setting up Massif in a development environment as described in [https://github.com/FTSRG/massif/wiki/DevelopersGuide](https://github.com/FTSRG/massif/wiki/DevelopersGuide), but oomph stops the setup with the following error:

`ERROR: org.eclipse.equinox.p2.director code=10053 Cannot complete the install because one or more required items could not be found.`

`ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1502839027432`

`ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: artificial_root 1.0.0.v1502839027432 requires 'org.eclipse.viatra.query.sdk.feature.source.feature.group 0.0.0' but it could not be found`

Yet, Viatra was downloaded and installed in my development environment during what was executed of the setup process.

Cheers.

**Comment by cevacu** [comment]
Hi,

I am trying to import a Simulink model in eclipse using the steps described in the user guide. However, when I tried to import the model in eclipse I got the following message: "No running MATLAB server was found with the given parameters specified in Window/Preference/Simulink Preferences". I am using as server name the name the Matlab script gave me, but it is not working. I would appreciate if you could help me to solve this problem.

Thank you.

**Comment by imbur** [comment]
First of all, thank you for your interest in Massif.

@afpaz There was a discussion regarding setting up the development environment under [issue #48](https://github.com/viatra/massif/issues/48). Could you please take a look at the conversation and try setting up your environment accordingly?
There is also an ongoing work on the `matlab-engine` branch that aims to use [the official Java interface](https://www.mathworks.com/help/matlab/matlab-engine-api-for-java.html) to interact with MATLAB. Currently there is work in progress, but later you might find it useful.

@cevacu Based on your comment it seems you are trying to use Massif with the Command Evaluation Server. Please open a new Github issue, and provide more details, such as:
- Operating system you are running
- Eclipse version you are using
- Matlab console output
- Preferences you provide
- Eclipse console log (start Eclipse from the command line using -colsoleLog)

**Comment by imbur** [comment]
Stateflow support is only a planned feature, but currently, we do not provide it.

**Comment by cevacu** [comment]
Thank you @imbur for your answer. 

Operating system you are running: Windows 10
Eclipse version you are using: Mars.2
Matlab console output:
setup_remote

ver =

r2016a

Configuration path not provided, considering the following path: C:\Users\Camilo\Documents\Paz\matlab\matlabserverconfig.properties
Host address = 127.0.0.1
Host port: 1098
Debug mode: null
Starting Matlab RMI Server...
-----------------------------
Address = 127.0.0.1
port = 1098
serviceName = MatlabModelProviderr2016a1684
-----------------------------

Matlab RMI Server Started!

Preferences you provide:
Host ip address: 127.0.0.1
Host port number: 1098
Server name: MatlabModelProviderr2016a1684
Matlab connector: Command evaluation server

I tried using the Eclipse started from console, but unfortunately I got the same error. I would appreciate any help you could give me.

Thank you.

**Comment by imbur** [comment]
@cevacu Do you happened to run the example import/export JUnit plug-in tests? For those, the service name shall be set in the corresponding `.properties` file.
And again, I ask you to please open a new issue if your problem still persists, instead of hijacking this discussion.

**Comment by imbur** [comment]
Sorry, I was wrong: for the examples, set the preferences here: https://github.com/viatra/massif/blob/master/examples/hu.bme.mit.massif.examples.api/src/hu/bme/mit/massif/examples/api/settings/ImporterExampleSettings.java and here https://github.com/viatra/massif/blob/master/examples/hu.bme.mit.massif.examples.api/src/hu/bme/mit/massif/examples/api/settings/ExporterExampleSettings.java

**Comment by afpaz** [comment]
Thank you @imbur for your reply.

> There was a discussion regarding setting up the development environment under issue #48. Could you please take a look at the conversation and try setting up your environment accordingly?

I followed the steps in issue #48 but got some build errors. I tried them using Eclipse Mars, Neon and Oxygen, and with all I got the same result. I had to use a different version of VIATRA from the one you suggest in issue #48, though, as version 1.5 is no longer available in [http://download.eclipse.org/viatra/updates/release/](http://download.eclipse.org/viatra/updates/release/). The only one that is available now is 1.6.1.

I'm getting the following error in the projects:

- `massif-matlabcontrol-runtime`
- `massif-communication-runtime`
- `massif-commandevaluation-runtime`

`Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-toolchains-plugin:1.1:toolchain (execution: default, phase: validate)`

There is also a build error in the project `hu.bme.mit.massif.examples.oslc`:

`Missing artifact net.oauth.core:oauth-httpclient4:jar:20090617`

Any suggestions on how to address these errors?

> There is also an ongoing work on the matlab-engine branch that aims to use the official Java interface to interact with MATLAB. Currently there is work in progress, but later you might find it useful.

Is there a tentative date when to expect this feature to be released?

> Stateflow support is only a planned feature, but currently, we do not provide it.

I can work on this feature since it's something I need and later on submit it to the project.

**Comment by abelhegedus** [comment]
> I had to use a different version of VIATRA from the one you suggest in issue #48, though, as version 1.5 is no longer available in http://download.eclipse.org/viatra/updates/release/. The only one that is available now is 1.6.1.

Earlier VIATRA versions _are_ still available, but if you used "Install new software", it is possible that you have selected "only show latest version". The above URL is a composite update site, containing all releases (see http://download.eclipse.org/viatra/updates/release/?d in a browser), but you can use a specific versions update site as well, e.g. http://download.eclipse.org/viatra/updates/release/1.5.3/

> Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-toolchains-plugin:1.1:toolchain (execution: default, phase: validate)

This is OK, those are Maven only projects, you can close them. To get rid of the error, you would have to install M2E and the Tycho M2E extension in Eclipse.

> There is also a build error in the project hu.bme.mit.massif.examples.oslc

Yes, the OSLC example is also not part of the build and unless you want to experiment with our OSLC prototype, you can close it also.

> I can work on this feature since it's something I need and later on submit it to the project.

That's great to hear, feel free to ask for any input you need to get going.

**Comment by abelhegedus** [comment]
Closing for now, added to [planning](https://github.com/viatra/massif/wiki/Planning).
