### ISSUE TITLE
Layout issues import dialogs

### ISSUE THREAD

**Issue by ujhelyiz** [viatra/massif#61]
When experimenting with the importer, it took me some time to figure out that something is wrong with layouts (at least on macOS): the Result Model Name field was not visible (see attached screenshot) and I am not allowed to resize this dialog. This was caused by explicitly setting the sizes of dialogs in pixel instead of asking for its recommended size.

![import](https://user-images.githubusercontent.com/251892/32773717-5a063056-c92a-11e7-91b9-738e4b04a0a0.png)

**Comment by ujhelyiz** [comment]
I have updated the sizing of dialogs by using the pack method provided by controls.

@imbur, @abelhegedus could one of you verify that this does not break layouts on Windows? Thanks.

**Comment by imbur** [comment]
Thanks for reporting and fixing this. I can confirm it was an issue on Linux as well, now it works fine. Appearance under Windows still needs to be confirmed.

**Comment by ujhelyiz** [comment]
In the machine of @lunkpeter we have seen that it works on Windows machines as well.

I have also added this commit to the master branch as well. Closing the issue as fixed.
