### ISSUE TITLE
Cannot import Simulink model

### ISSUE THREAD

**Issue by jonmmar** [viatra/massif#71]
I have the following installation on Neon
Massif 0.5.0.201606031221	
EMF-IncQuery	1.1.0.201512031022
jre1.8.0_151

The Matlab RMI has successfully started, and I copied the serviceName into the appropriate field in the Eclipse preferences.

When I attempt to import a Simulink model, nothing appears to happen, and no error or warning messages are presented in Eclipse or in Matlab.  The GUI brought up from the right context menu is also different from what is shown in the User Guide:  there is no field for "result model name".

Any recommendations on how to fix this?

**Comment by abelhegedus** [comment]
Can you attach a screenshot of the GUI as you see it?

If you use scaling on a HiDPI monitor, you may run into the issue that the size of the dialog is fixed but UI elements are not visible as they cannot fit (we fixed this in 32ae721cd07b7a16546024d2dd50fa1ce7beba99 ).

Did you set the target directory to a a location that is part of the Eclipse workspace? Did you check the filesystem if a file was created? You can also check the Error log (Window -> Show View) for any errors.

Also, you can use [debug mode](https://github.com/viatra/massif/wiki/UserGuide#enable-debug-mode) to check whether any commands are executed on the Matlab side.

**Comment by abelhegedus** [comment]
Closing for now, please reopen with specifics if still relevant. Thanks!
