### ISSUE TITLE
Review Simulink metamodel

### ISSUE THREAD

**Issue by imbur** [viatra/massif#8]
Investigate simplification possibilities:
- Ports and portblocks
- Buses
- Block container abstraction for SubSystem and SimulinkModel
- Rename SimulinkModel to Model

**Comment by imbur** [comment]
Parameters (properties):
 - In Simulink, blocks have **Parameter**s that are called **Properti**es in the EMF metamodel
 - `PropertyType` has only `STRING`, `INTEGER`, and `DOUBLE` literals that can be used to indicate parameter types, however, there is a wider scale for them (`struct`, `cell`, arrays of different kinds, etc.)
 - `INTEGER` is not the best name for a parameter type - even though the function `class` in MATLAB can return `int8` (and `uint8`, as well as wider integer types), but they are used for integer arrays
 - As of now, the type `Compatibility` is not supported by `MatlabEngine`, so the Compatibility parameter cannot be queried using that connector

**Comment by imbur** [comment]
I would like to add that after the recent updates to parameter importing (that is, all parameters are queried for a block), the _parameter source_ is not necessarily complete. Currently, next to `DIALOG` and `MASK` source types, the `INTERNAL` source type might be a too general/imprecise description.

**Comment by imbur** [comment]
[This page](https://www.mathworks.com/help/simulink/slref/common-block-parameters.html) summarizes the available port types under the `Ports` parameter description. We should also add support for `State`, `Ifaction`, and `Reset` ports, because it may cause issues during export (as pointed out in #126).

For the time being, `LConn` and `RConn` types can be ignored, since Massif does not support SimScape (yet), and these two types are used during physical modeling.

**Comment by abelhegedus** [comment]
Sounds good!

**Comment by imbur** [comment]
As discussed with @abelhegedus, we will remove the parameter source attribute from the parameter class because with the parameter filtering mechanism arbitrary parameters can be selected for importing, and the current three parameter source categories (dialog, mask, and internal) are too general.

**Comment by imbur** [comment]
Additionally, as requested in #30, we will add parameters to ports.

**Comment by abelhegedus** [comment]
New metamodel changes should be created as separate issues.
